"""Static seed data: tech vocabulary (section 5.5) and accepted variants (section 8.5).

Phonemes use the espeak-ng en-us IPA inventory (see api/pronunciation/g2p.py):
phones separated by spaces, words by " | ", no stress marks.
"""

# (term, say_as, domain, common_mistake_note)
# say_as: spelling fed to espeak when the written form would be mispronounced (acronyms,
# brand names). None = use the term itself.
TECH_VOCABULARY: list[tuple[str, str | None, str, str | None]] = [
    # --- general / architecture
    ("API", "A P I", "api", "Spell the letters: ay-pee-eye. Not 'ah-pee-ee'."),
    ("architecture", None, "architecture", "Starts with /k/: AR-ki-tek-cher, not 'ar-shi-'."),
    ("microservices", None, "architecture", "MY-kro, with /aɪ/; stress on the first syllable."),
    ("monolith", None, "architecture", "MON-o-lith; final /θ/, not /t/."),
    ("scalability", None, "architecture", "ska-la-BIL-i-ty; stress on BIL."),
    ("scalable", None, "architecture", "SKAY-la-bul; no extra vowel before /s/ ('es-calable')."),
    ("availability", None, "architecture", "a-vay-la-BIL-i-ty."),
    ("reliability", None, "architecture", "ri-lai-a-BIL-i-ty; /aɪ/ in 'li'."),
    ("throughput", None, "architecture", "THROO-put; starts with /θ/, not /t/ or /f/."),
    ("latency", None, "architecture", "LAY-ten-see; /eɪ/, not 'lah-'."),
    ("bottleneck", None, "architecture", "BOT-ul-nek; flap t in American English."),
    ("tradeoff", "trade off", "architecture", "TRADE-off; stress on the first part."),
    ("trade-offs", "trade offs", "architecture", None),
    ("requirements", None, "architecture", "ri-KWAI-er-ments."),
    ("stateless", None, "architecture", "STAYT-less; no epenthetic 'es-'."),
    ("stateful", None, "architecture", "STAYT-ful; no epenthetic 'es-'."),
    ("event-driven", "event driven", "architecture", "ee-VENT; stress on the second syllable."),
    ("fault tolerance", None, "architecture", None),
    ("redundancy", None, "architecture", "ri-DUN-dan-see."),
    ("single point of failure", None, "architecture", "FAIL-yer."),
    ("high availability", None, "architecture", "Pronounce the initial /h/."),
    ("horizontal scaling", None, "architecture", "Pronounce the initial /h/; hor-i-ZON-tal."),
    ("vertical scaling", None, "architecture", "VER-ti-kal."),
    ("deployment", None, "infra", "de-PLOY-ment; stress on PLOY."),
    ("development", None, "general", "de-VEL-op-ment; stress on VEL, not on 'MENT'."),
    ("developer", None, "general", "de-VEL-o-per."),
    ("computer", None, "general", "com-PYU-ter; stress on PYU."),
    ("algorithm", None, "general", "AL-go-ri-thm; ends with /ð/ + /m/, no extra vowel."),
    ("asynchronous", None, "concurrency", "ay-SIN-kro-nus; stress on SIN."),
    ("synchronous", None, "concurrency", "SIN-kro-nus."),
    ("concurrency", None, "concurrency", "kon-KUR-en-see."),
    ("parallelism", None, "concurrency", "PAR-a-lel-iz-um."),
    ("thread", None, "concurrency", "Starts with /θ/, not /t/: 'thred'."),
    ("thread pool", None, "concurrency", None),
    ("race condition", None, "concurrency", None),
    ("deadlock", None, "concurrency", "DED-lok; short /ɛ/."),
    ("mutex", None, "concurrency", "MYOO-teks."),
    ("lock", None, "concurrency", None),
    ("semaphore", None, "concurrency", "SEM-a-for."),
    ("event loop", None, "concurrency", None),
    ("idempotent", "eyedempohtent", "api", "eye-dem-POH-tent; stress on POH."),
    ("idempotency", "eyedempohtensee", "api", "eye-dem-POH-ten-see."),
    ("endpoint", None, "api", "END-point."),
    ("REST", None, "api", "One syllable: 'rest', no final vowel ('resti')."),
    ("RESTful", "rest ful", "api", None),
    ("GraphQL", "graph Q L", "api", "GRAF-kyoo-el."),
    ("gRPC", "G R P C", "api", "jee-ar-pee-see."),
    ("JSON", "jay son", "api", "JAY-son."),
    ("payload", None, "api", "PAY-lohd."),
    ("pagination", None, "api", "pa-ji-NAY-shun; /dʒ/ sound."),
    ("rate limiting", None, "api", "RAYT LIM-i-ting."),
    ("authentication", None, "security", "aw-then-ti-KAY-shun; /θ/ in 'then'."),
    ("authorization", None, "security", "aw-thor-i-ZAY-shun; /θ/."),
    ("OAuth", "oh auth", "security", "OH-awth; /θ/ at the end."),
    ("token", None, "security", "TOH-ken."),
    ("encryption", None, "security", "en-KRIP-shun."),
    ("hash", None, "security", "Pronounce the initial /h/ (not silent, not Portuguese 'r')."),
    ("hashing", None, "security", "Pronounce the initial /h/."),
    ("certificate", None, "security", "ser-TIF-i-kit."),
    ("versioning", None, "api", "VER-zhun-ing."),
    ("backward compatible", None, "api", "com-PAT-i-bul."),
    ("webhook", None, "api", None),
    ("schema", None, "databases", "SKEE-ma; starts with /sk/, no 'es-'."),
    ("migration", None, "databases", "my-GRAY-shun."),
    # --- databases
    ("database", None, "databases", "DAY-ta-base (or DAT-a-base); stress on the first syllable."),
    ("data", None, "databases", "DAY-ta or DA-ta (flap t); not 'DAH-chee'."),
    ("query", None, "databases", "KWEER-ee."),
    ("queries", None, "databases", None),
    ("index", None, "databases", "IN-deks; no final vowel."),
    ("indexes", None, "databases", None),
    ("PostgreSQL", "post gres Q L", "databases", "POST-gres-kyoo-el."),
    ("Postgres", "post gres", "databases", None),
    ("MySQL", "my S Q L", "databases", "my-ess-kyoo-el."),
    ("SQL", "sequel", "databases", "SEE-kwel or ess-kyoo-el."),
    ("NoSQL", "no sequel", "databases", None),
    ("MongoDB", "mongo D B", "databases", None),
    ("DynamoDB", "dynamo D B", "databases", "DY-na-mo; /aɪ/."),
    ("Cassandra", None, "databases", None),
    ("Elasticsearch", "elastic search", "databases", None),
    ("transaction", None, "databases", "tran-ZAK-shun."),
    ("ACID", "acid", "databases", "Said as the word 'acid': AS-id."),
    ("isolation level", None, "databases", "eye-so-LAY-shun."),
    ("normalization", None, "databases", None),
    ("denormalization", None, "databases", None),
    ("sharding", None, "databases", "SHAR-ding; /ʃ/."),
    ("shard", None, "databases", None),
    ("partitioning", None, "databases", "par-TISH-un-ing."),
    ("replica", None, "databases", "REP-li-ka; stress on the first syllable."),
    ("replication", None, "databases", "rep-li-KAY-shun."),
    ("read replica", None, "databases", None),
    ("primary key", None, "databases", "PRY-mer-ee."),
    ("foreign key", None, "databases", "FOR-in; the 'g' is silent."),
    ("join", None, "databases", None),
    ("ORM", "O R M", "databases", None),
    # --- caching
    ("cache", None, "caching", "Sounds like 'cash' /kæʃ/, not 'cash-ay' or 'catch'."),
    ("caching", None, "caching", "KASH-ing."),
    ("cache miss", None, "caching", None),
    ("cache hit", None, "caching", "Pronounce the /h/ in 'hit'."),
    ("invalidation", None, "caching", "in-val-i-DAY-shun."),
    ("eviction", None, "caching", "i-VIK-shun."),
    ("write-through", "write through", "caching", "/θ/ in 'through'."),
    ("write-back", "write back", "caching", None),
    ("TTL", "T T L", "caching", None),
    ("Redis", "reddis", "caching", "RED-iss."),
    ("Memcached", "mem cashed", "caching", "MEM-kasht."),
    ("CDN", "C D N", "caching", None),
    # --- messaging
    ("queue", None, "messaging", "Sounds like the letter Q /kjuː/, not 'kweh-weh'."),
    ("message queue", None, "messaging", None),
    ("Kafka", None, "messaging", "KAHF-ka."),
    ("RabbitMQ", "rabbit M Q", "messaging", None),
    ("broker", None, "messaging", "BROH-ker."),
    ("consumer", None, "messaging", "kon-SOO-mer."),
    ("producer", None, "messaging", "pro-DOO-ser."),
    ("publish-subscribe", "publish subscribe", "messaging", None),
    ("pub/sub", "pub sub", "messaging", None),
    ("topic", None, "messaging", "TOP-ik."),
    ("offset", None, "messaging", None),
    ("at-least-once", "at least once", "messaging", None),
    ("exactly-once", "exactly once", "messaging", None),
    ("dead letter queue", None, "messaging", None),
    ("backpressure", "back pressure", "messaging", None),
    ("retry", None, "messaging", "ree-TRY."),
    ("exponential backoff", None, "messaging", "ex-po-NEN-shul."),
    # --- consistency / distributed systems
    ("consistency", None, "consistency", "kon-SIS-ten-see."),
    ("eventual consistency", None, "consistency", "i-VEN-choo-al."),
    ("consensus", None, "consistency", "kon-SEN-sus."),
    ("Raft", None, "consistency", None),
    ("Paxos", None, "consistency", None),
    ("quorum", None, "consistency", "KWOR-um."),
    ("leader election", None, "consistency", None),
    ("distributed", None, "consistency", "dis-TRIB-yoo-ted; stress on TRIB."),
    ("partition tolerance", None, "consistency", None),
    ("CAP theorem", "cap theorem", "consistency", "THEER-um; /θ/."),
    ("clock skew", None, "consistency", None),
    ("two-phase commit", "two phase commit", "consistency", None),
    ("saga", None, "consistency", "SAH-ga."),
    # --- infra / cloud
    ("Kubernetes", None, "infra", "koo-ber-NET-eez; stress on NET."),
    ("Docker", None, "infra", "DOK-er."),
    ("container", None, "infra", "kon-TAY-ner."),
    ("Nginx", "engine x", "infra", "Said 'engine-ex'."),
    ("load balancer", None, "infra", "BAL-an-ser."),
    ("reverse proxy", None, "infra", None),
    ("autoscaling", None, "infra", None),
    ("AWS", "A W S", "infra", "ay-double-yoo-ess."),
    ("Azure", None, "infra", "AZH-er."),
    ("serverless", None, "infra", None),
    ("Lambda", None, "infra", "LAM-da; the 'b' is silent."),
    ("S3", "S three", "infra", "/θ/ in 'three'."),
    ("CI/CD", "C I C D", "infra", None),
    ("pipeline", None, "infra", None),
    ("Terraform", None, "infra", None),
    ("observability", None, "infra", "ob-zer-va-BIL-i-ty."),
    ("monitoring", None, "infra", None),
    ("logging", None, "infra", None),
    ("metrics", None, "infra", "MET-riks."),
    ("Prometheus", None, "infra", "pro-MEE-thee-us; /θ/."),
    ("Grafana", None, "infra", None),
    ("health check", None, "infra", "Pronounce the /h/ and the /θ/ in 'health'."),
    ("rollback", None, "infra", None),
    ("canary deployment", None, "infra", None),
    ("blue-green deployment", "blue green deployment", "infra", None),
    # --- networking
    ("HTTP", "H T T P", "networking", "aitch-tee-tee-pee."),
    ("HTTPS", "H T T P S", "networking", None),
    ("TCP", "T C P", "networking", None),
    ("UDP", "U D P", "networking", None),
    ("DNS", "D N S", "networking", None),
    ("WebSocket", "web socket", "networking", None),
    ("bandwidth", None, "networking", "BAND-width; final /θ/."),
    ("protocol", None, "networking", "PRO-to-kol."),
    ("router", None, "networking", "ROW-ter (American)."),
    # --- languages / tools
    ("Node.js", "node J S", "languages", None),
    ("TypeScript", "type script", "languages", None),
    ("JavaScript", "java script", "languages", None),
    ("Python", None, "languages", "PY-thon; /θ/, not /t/."),
    ("Django", "jango", "languages", "The 'D' is silent: JANG-go."),
    ("FastAPI", "fast A P I", "languages", None),
    ("npm", "N P M", "languages", None),
    ("GitHub", "git hub", "languages", "Pronounce the /h/ in 'hub'."),
    ("framework", None, "languages", None),
    ("library", None, "languages", "LY-brer-ee."),
    ("garbage collection", None, "languages", "GAR-bij."),
    ("memory leak", None, "languages", None),
    ("refactoring", None, "languages", None),
    ("unit test", None, "testing", None),
    ("integration test", None, "testing", None),
    # --- estimation
    ("estimate", None, "estimation", "Noun: ES-ti-mit; verb: ES-ti-mayt."),
    ("estimation", None, "estimation", "es-ti-MAY-shun."),
    ("requests per second", None, "estimation", "Keep the final consonant clusters: re-KWESTS, SEK-und."),
    ("gigabyte", None, "estimation", "GIG-a-bite; hard /g/."),
    ("terabyte", None, "estimation", None),
    ("petabyte", None, "estimation", None),
    ("millisecond", None, "estimation", None),
    ("thousand", None, "estimation", "Starts with /θ/: THOW-zand."),
    ("three", None, "estimation", "Starts with /θ/, not /t/ or /f/."),
    ("third", None, "estimation", "Starts with /θ/."),
    ("hundred", None, "estimation", "Pronounce the initial /h/."),
]

# (word, expected, accepted, note) — word None = general rule applied to any word.
# Phoneme sequences use the espeak en-us inventory, space-separated.
ACCEPTED_VARIANTS: list[tuple[str | None, str, str, str]] = [
    # American flap t/d
    (None, "t", "ɾ", "American flap t between vowels (water, better)."),
    (None, "ɾ", "t", "Careful speech: a clear /t/ is fine where espeak predicts a flap."),
    (None, "d", "ɾ", "American flap d between vowels (ladder, ready)."),
    (None, "ɾ", "d", "Careful speech: a clear /d/ where espeak predicts a flap."),
    ("water", "w ɔː ɾ ɚ", "w ɑː ɾ ɚ", "Common American vowel in 'water'."),
    ("better", "b ɛ ɾ ɚ", "b ɛ t ɚ", "Clear /t/ is acceptable."),
    # data
    ("data", "d eɪ ɾ ə", "d æ ɾ ə", "'data' as /dætə/ is standard too."),
    ("data", "d eɪ ɾ ə", "d eɪ t ə", "Clear /t/ is acceptable."),
    ("data", "d eɪ ɾ ə", "d ɑː ɾ ə", "/dɑːtə/ is an accepted variant."),
    ("database", "d eɪ ɾ ə b eɪ s", "d æ ɾ ə b eɪ s", "Same variation as 'data'."),
    # either / neither
    ("either", "iː ð ɚ", "aɪ ð ɚ", "/aɪðɚ/ is also standard."),
    ("neither", "n iː ð ɚ", "n aɪ ð ɚ", "/naɪðɚ/ is also standard."),
    # route / router
    ("route", "ɹ aʊ t", "ɹ uː t", "/ruːt/ is also standard."),
    ("router", "ɹ aʊ ɾ ɚ", "ɹ uː ɾ ɚ", "/ruːtɚ/ is also heard."),
    # schedule
    ("schedule", "s k ɛ dʒ uː l", "s k ɛ dʒ ʊ l", "Reduced vowel in the second syllable."),
    ("schedule", "s k ɛ dʒ uː l", "ʃ ɛ dʒ uː l", "British /ʃɛdjuːl/ — understandable, not an error."),
    # other common alternations
    ("often", "ɔ f ə n", "ɔ f t ə n", "Pronouncing the /t/ is accepted."),
    ("tomato", "t ə m eɪ ɾ oʊ", "t ə m ɑː ɾ oʊ", None),
    ("process", "p ɹ ɑː s ɛ s", "p ɹ oʊ s ɛ s", "/proʊsɛs/ is also used."),
    ("privacy", "p ɹ aɪ v ə s i", "p ɹ ɪ v ə s i", "British-style /prɪvəsi/."),
    ("aunt", "æ n t", "ɑː n t", None),
    ("economic", "ɛ k ə n ɑː m ɪ k", "iː k ə n ɑː m ɪ k", None),
    ("lever", "l ɛ v ɚ", "l iː v ɚ", None),
    # noun/verb pairs: G2P can't know which one was meant, both are correct
    ("use", "j uː s", "j uː z", "Verb 'use' ends in /z/; the noun in /s/."),
    ("used", "j uː z d", "j uː s t", "'used to' is /juːst/."),
    ("duplicates", "d uː p l ᵻ k eɪ t s", "d uː p l ɪ k ə t s", "Noun 'duplicates' ends in /-kəts/."),
    ("duplicate", "d uː p l ᵻ k eɪ t", "d uː p l ɪ k ə t", "Noun/adjective 'duplicate' ends in /-kət/."),
    ("estimate", "ɛ s t ᵻ m eɪ t", "ɛ s t ɪ m ə t", "Noun 'estimate' ends in /-mət/."),
    ("estimates", "ɛ s t ᵻ m eɪ t s", "ɛ s t ɪ m ə t s", "Noun 'estimates' ends in /-məts/."),
    ("separate", "s ɛ p ɚ ɹ eɪ t", "s ɛ p ɹ ə t", "Adjective 'separate' is /ˈsɛprət/."),
    ("aggregate", "æ ɡ ɹ ᵻ ɡ eɪ t", "æ ɡ ɹ ɪ ɡ ə t", "Noun 'aggregate' ends in /-ɡət/."),
    ("approximate", "ɐ p ɹ ɑː k s ɪ m eɪ t", "ɐ p ɹ ɑː k s ɪ m ə t", "Adjective 'approximate' ends in /-mət/."),
    ("close", "k l oʊ z", "k l oʊ s", "Adjective 'close' ends in /s/."),
    ("record", "ɹ ɛ k ɚ d", "ɹ ᵻ k ɔːɹ d", "Verb 'record' is /rɪˈkɔːrd/."),
    ("present", "p ɹ ɛ z ən t", "p ɹ ᵻ z ɛ n t", "Verb 'present' is /prɪˈzɛnt/."),
    # common American alternatives
    ("want", "w ɔ n t", "w ɑː n t", "American /wɑːnt/."),
    ("want", "w ɔ n t", "w ɑː n", "Fast speech: /wɑːn/ before 'to'."),
    ("asynchronously", "ɐ s ɪ ŋ k ɹ ə n ə s l i", "eɪ s ɪ ŋ k ɹ ə n ə s l i", "/eɪ-/ is a common pronunciation."),
    ("asynchronous", "ɐ s ɪ ŋ k ɹ ə n ə s", "eɪ s ɪ ŋ k ɹ ə n ə s", "/eɪ-/ is a common pronunciation."),
    ("prometheus", "p ɹ oʊ m iː θ ɪ ə s", "p ɹ ə m iː θ i ə s", "Reduced /prə-/ is standard."),
    ("actually", "æ k tʃ uː əl i", "æ k ʃ uː əl i", "/ˈækʃuəli/ is very common."),
    ("actually", "æ k tʃ uː əl i", "æ k ʃ l i", "Fast speech: /ˈækʃli/."),
    ("actually", "æ k tʃ uː əl i", "æ k ʃ ʊ l i", "Fast speech: /ˈækʃʊli/."),
    # the / a
    ("the", "ð ə", "ð i", "'the' as /ði/ before vowels or for emphasis."),
    ("the", "ð ə", "ð iː", "Emphatic 'the'."),
    ("a", "ə", "eɪ", "Emphatic 'a'."),
    ("to", "t uː", "t ə", "Weak form of 'to'."),
    ("for", "f ɔː ɹ", "f ɚ", "Weak form of 'for'."),
    ("and", "æ n d", "ə n", "Weak form of 'and'."),
    ("and", "æ n d", "ə n d", "Weak form of 'and'."),
    ("can", "k æ n", "k ə n", "Weak form of 'can'."),
    ("of", "ʌ v", "ə v", "Weak form of 'of'."),
    ("of", "ʌ v", "ə", "Weak form of 'of' in connected speech."),
    ("you", "j uː", "j ə", "Weak form of 'you'."),
    # connected-speech reductions
    ("want to", "w ɔ n t | t uː", "w ɑː n ə", "'wanna' in connected speech."),
    ("going to", "ɡ oʊ ɪ ŋ | t uː", "ɡ ʌ n ə", "'gonna' in connected speech."),
    ("kind of", "k aɪ n d | ʌ v", "k aɪ n d ə", "'kinda' in connected speech."),
    ("sort of", "s ɔː ɹ t | ʌ v", "s ɔː ɹ ɾ ə", "'sorta' in connected speech."),
    ("got to", "ɡ ɑː t | t uː", "ɡ ɑː ɾ ə", "'gotta' in connected speech."),
    ("have to", "h æ v | t uː", "h æ f t ə", "'hafta' in connected speech."),
    ("let me", "l ɛ t | m iː", "l ɛ m i", "'lemme' in connected speech."),
    # schwa in unstressed syllables
    (None, "ɪ", "ə", "Unstressed /ɪ/ often reduces to schwa."),
    (None, "ʌ", "ə", "Unstressed /ʌ/ reduces to schwa."),
    (None, "ɐ", "ə", "espeak's /ɐ/ is a schwa-like reduced vowel."),
    (None, "ə", "ɐ", "Schwa heard as the recognizer's /ɐ/: the same reduced vowel."),
    (None, "ʊ", "ʌ", "Unstressed /ʊ/ often reduces (throughput, output)."),
    (None, "ʊ", "ə", "Unstressed /ʊ/ often reduces to schwa."),
    (None, "ə", "ɪ", "Unstressed schwa realized as /ɪ/ (roses, wanted)."),
    (None, "ɚ", "ə ɹ", "Rhotic schwa realized as two segments."),
    (None, "i", "ɪ", "Final unstressed /i/ (happy) vs /ɪ/."),
    (None, "ɪ", "i", "Unstressed /ɪ/ tensed to /i/ (queries, cities) — normal in American English."),
    (None, "iː", "i", "Final /iː/ vs /i/ (idempotency, latency): same sound in running speech."),
    (None, "oʊ", "o", "Monophthongal /o/ in fast speech."),
    (None, "eɪ", "e", "Monophthongal /e/ in fast speech."),
]
