"""WebSocket integration test with synthetic speech generated by Kokoro (section 13).

Needs Postgres (make db-up) and the model server (make models). The LLM is replaced by
a scripted fake so the test is deterministic and free. Skipped when services are down.
"""

import asyncio
import json
import time

import httpx
import numpy as np
import pytest
import websockets

from api.config import get_settings
from api.realtime.orchestrator import AUDIO_HEADER
from model_server.framing import read_frames
from tests.conftest import BASE, PORT, FakeLLM, is_up, track

FRAME_SAMPLES = 320  # 20 ms at 16 kHz

pytestmark = pytest.mark.skipif(
    not is_up(f"{get_settings().model_server_url}/health"), reason="model server not running"
)


async def synth_16k(text: str) -> bytes:
    """Kokoro speech (24 kHz) resampled to the 16 kHz PCM16 the browser would send."""
    pcm = b""
    async with httpx.AsyncClient(base_url=get_settings().model_server_url, timeout=30) as c:
        async with c.stream("POST", "/tts", json={"text": text}) as r:
            async for frame in read_frames(r.aiter_bytes()):
                if isinstance(frame, bytes):
                    pcm += frame
    a24 = np.frombuffer(pcm, dtype="<i2").astype(np.float32)
    t16 = np.arange(0, len(a24) / 24_000, 1 / 16_000)
    a16 = np.interp(t16, np.arange(len(a24)) / 24_000, a24)
    # trim Kokoro's leading/trailing silence (a browser VAD wraps just the speech), keep 100 ms
    voiced = np.flatnonzero(np.abs(a16) > 500)
    if len(voiced):
        a16 = a16[max(0, voiced[0] - 1600) : voiced[-1] + 1600]
    return a16.astype("<i2").tobytes()


class Client:
    def __init__(self, ws) -> None:
        self.ws = ws
        self.log: list[dict] = []
        self.audio: list[tuple[int, int]] = []

    async def until(self, pred, timeout: float = 15.0) -> dict:
        """Read messages until ``pred(msg)`` is true; record everything."""
        deadline = time.monotonic() + timeout
        while True:
            remaining = deadline - time.monotonic()
            try:
                if remaining <= 0:
                    raise TimeoutError
                raw = await asyncio.wait_for(self.ws.recv(), remaining)
            except TimeoutError:
                raise AssertionError(
                    f"timeout; got {[m.get('type') + ':' + str(m.get('state', '')) for m in self.log][-15:]}"
                ) from None
            if isinstance(raw, bytes):
                turn_id, idx, _ = AUDIO_HEADER.unpack_from(raw)
                self.audio.append((turn_id, idx))
                continue
            msg = json.loads(raw)
            self.log.append(msg)
            if pred(msg):
                return msg

    async def drain(self, seconds: float = 0.3) -> None:
        """Record whatever arrives in the next ``seconds`` without waiting for anything."""
        try:
            await self.until(lambda m: False, timeout=seconds)
        except AssertionError:
            pass

    async def speak(self, pcm: bytes, realtime: bool = True, end: bool = True) -> None:
        await self.ws.send(json.dumps({"type": "vad", "event": "speech_start", "t": 0}))
        step = FRAME_SAMPLES * 2
        for i in range(0, len(pcm), step):
            await self.ws.send(pcm[i : i + step])
            if realtime:
                await asyncio.sleep(0.02)
        if end:
            await self.ws.send(json.dumps({"type": "vad", "event": "speech_end", "t": 0}))

    async def silence(self, seconds: float) -> None:
        frame = bytes(FRAME_SAMPLES * 2)
        for _ in range(int(seconds / 0.02)):
            await self.ws.send(frame)
            await asyncio.sleep(0.02)


def is_type(*types):
    return lambda m: m.get("type") in types


def state_is(state):
    return lambda m: m.get("type") == "state" and m.get("state") == state


async def open_session(llm: FakeLLM, use_llm, before_connect=None, **session) -> tuple[str, Client]:
    use_llm(llm)
    async with httpx.AsyncClient(base_url=BASE) as c:
        r = await c.post("/api/sessions", json={"type": "technical", **session})
        r.raise_for_status()
        session_id = track("interview_sessions", r.json()["id"])
    if before_connect:
        await before_connect(session_id)
    ws = await websockets.connect(f"ws://127.0.0.1:{PORT}/ws/interview/{session_id}", max_size=None)
    return session_id, Client(ws)


async def finish_greeting(client: Client) -> int:
    end = await client.until(is_type("tts_end"))
    await client.ws.send(json.dumps({"type": "playback_done", "turn_id": end["turn_id"]}))
    await client.until(state_is("LISTENING"))
    return end["turn_id"]


async def get_turns(session_id: str) -> list[dict]:
    async with httpx.AsyncClient(base_url=BASE) as c:
        return (await c.get(f"/api/sessions/{session_id}")).json()["turns"]


GREETING = "Hi, I'm Alex from the platform team. Tell me about a system you designed recently."
LONG = (
    "Great, thanks for sharing that with me. Now I would like to understand how you would scale "
    "the write path when traffic grows ten times. Please think about queues, caches and the "
    "database, and tell me which trade-offs you would accept along the way."
)


async def test_full_turn_and_reply(server, use_llm):
    llm = FakeLLM([GREETING, "Interesting. Why did you choose Redis for that?"])
    session_id, client = await open_session(llm, use_llm)
    try:
        first = await client.until(is_type("tts_sentence"))
        assert first["words"] and first["words"][0]["char_start"] == 0
        await finish_greeting(client)

        answer = await synth_16k("I designed a URL shortener using Redis and PostgreSQL.")
        await client.speak(answer, realtime=False)
        final = await client.until(is_type("transcript_final"))
        assert "postgresql" in final["text"].lower()  # (Kokoro mispronounces "Redis")
        await client.until(is_type("tts_sentence"))
        latency = await client.until(is_type("latency"))
        assert latency["total_ms"] < 4000

        # the LLM saw the candidate's words as the last user message
        last_user = next(m for m in reversed(llm.calls[-1]) if m["role"] == "user")
        assert "postgresql" in last_user["content"].lower()
        # every audio chunk belongs to a turn the server announced
        assert {t for t, _ in client.audio} <= {1, 2}
    finally:
        await client.ws.close()
    turns = await get_turns(session_id)
    assert [t["role"] for t in turns][:2] == ["interviewer", "candidate"]
    assert turns[1]["audio_ms"] > 1000


async def test_barge_in_records_spoken_text_and_informs_llm(server, use_llm):
    llm = FakeLLM([GREETING, LONG, "Sure. I asked how you would scale the write path."])
    session_id, client = await open_session(llm, use_llm)
    try:
        await finish_greeting(client)
        await client.speak(await synth_16k("I built a payments API in Node.js."), realtime=False)
        await client.until(is_type("transcript_final"))
        sentence = await client.until(is_type("tts_sentence"))
        await client.until(state_is("SPEAKING"))

        interruption = await synth_16k("Sorry, can you repeat the question please?")
        speak = asyncio.create_task(client.speak(interruption, realtime=True))
        await client.until(is_type("duck"), timeout=5)
        stop = await client.until(is_type("stop_playback"), timeout=5)
        assert stop["turn_id"] == sentence["turn_id"]
        # pretend the player was 3 words into the first sentence
        third_word = sentence["words"][2]
        await client.ws.send(json.dumps({
            "type": "interrupted", "turn_id": stop["turn_id"], "sentence_idx": 0,
            "char_offset": third_word["char_end"],
        }))
        await speak
        await client.until(is_type("transcript_final"))
        await client.until(is_type("tts_sentence"))

        msgs = llm.calls[-1]
        spoken = sentence["text"][: third_word["char_end"]]
        assert {"role": "assistant", "content": f"{spoken}—"} in msgs
        note = next(m for m in msgs[1:] if m["role"] == "system" and "did NOT hear" in m["content"])
        assert "trade-offs" in note["content"]  # the unsaid part
        # no audio for the interrupted turn after stop_playback
        stop_pos = client.log.index(stop)
        later_sentences = [m for m in client.log[stop_pos:] if m.get("type") == "tts_sentence"]
        assert all(m["turn_id"] > stop["turn_id"] for m in later_sentences)
    finally:
        await client.ws.close()
    await asyncio.sleep(0.3)
    turns = await get_turns(session_id)
    interrupted = [t for t in turns if t["interrupted"]]
    assert len(interrupted) == 1
    assert interrupted[0]["spoken_text"] == spoken
    assert interrupted[0]["interrupted_at_char"] == len(spoken)


async def test_backchannel_and_noise_do_not_interrupt(server, use_llm):
    llm = FakeLLM([GREETING, LONG])
    session_id, client = await open_session(llm, use_llm)
    try:
        await finish_greeting(client)
        await client.speak(await synth_16k("I worked on a billing system."), realtime=False)
        await client.until(state_is("SPEAKING"), timeout=20)

        # cough / noise: < 400 ms
        await client.ws.send(json.dumps({"type": "vad", "event": "speech_start", "t": 0}))
        await client.silence(0.1)
        await client.ws.send(json.dumps({"type": "vad", "event": "speech_end", "t": 0}))
        await client.until(is_type("unduck"), timeout=3)

        # backchannel
        # (Kokoro cannot say "uh-huh"/"mm-hmm" intelligibly; those need a manual check)
        await client.speak(await synth_16k("Yeah, right."), realtime=True)
        await client.until(is_type("unduck"), timeout=5)
        await client.speak(await synth_16k("Got it."), realtime=True)
        await client.until(is_type("unduck"), timeout=5)
        assert not any(m.get("type") == "stop_playback" for m in client.log)
    finally:
        await client.ws.close()


async def test_pause_inside_incomplete_phrase_does_not_end_turn(server, use_llm):
    llm = FakeLLM([GREETING, "Okay, go on."])
    session_id, client = await open_session(llm, use_llm)
    try:
        await finish_greeting(client)
        await client.speak(await synth_16k("So for the database layer I would use"), realtime=False)
        await client.silence(2.0)  # thinking pause
        await client.drain()
        assert not any(m.get("type") == "transcript_final" for m in client.log)
        assert len(llm.calls) == 1  # only the greeting
        await client.speak(await synth_16k("PostgreSQL with read replicas."), realtime=False)
        final = await client.until(is_type("transcript_final"), timeout=10)
        assert "would use" in final["text"].lower() and "replica" in final["text"].lower()
    finally:
        await client.ws.close()


async def test_push_to_talk(server, use_llm):
    llm = FakeLLM([GREETING, "Thanks."])
    session_id, client = await open_session(llm, use_llm)
    try:
        await client.ws.send(json.dumps({"type": "set_mode", "mode": "push_to_talk"}))
        await finish_greeting(client)
        await client.ws.send(json.dumps({"type": "ptt", "event": "down"}))
        pcm = await synth_16k("My main stack is Python and TypeScript.")
        for i in range(0, len(pcm), FRAME_SAMPLES * 2):
            await client.ws.send(pcm[i : i + FRAME_SAMPLES * 2])
        await client.ws.send(json.dumps({"type": "ptt", "event": "up"}))
        final = await client.until(is_type("transcript_final"), timeout=5)
        assert "python" in final["text"].lower()
    finally:
        await client.ws.close()


async def test_turn_ends_even_if_the_browser_never_sends_speech_end(server, use_llm):
    """Regression: a missed speech_end from the browser VAD used to leave the turn open forever."""
    llm = FakeLLM([GREETING, "Thanks. What was the hardest part?"])
    session_id, client = await open_session(llm, use_llm)
    try:
        await finish_greeting(client)
        await client.speak(await synth_16k("I built a versioning system with Django REST framework."),
                           realtime=False, end=False)  # speech_start, speech... and no speech_end
        await client.silence(2.5)  # the mic keeps streaming silence
        final = await client.until(is_type("transcript_final"), timeout=10)
        assert "django" in final["text"].lower()
        await client.until(is_type("tts_sentence"), timeout=10)
    finally:
        await client.ws.close()


async def test_resuming_speech_during_transcription_still_ends_the_turn(server, use_llm):
    """Regression (real speech with pauses): speech_start arrives while the previous segment
    is still being transcribed. The turn must still end after the final pause."""
    llm = FakeLLM([GREETING, "Interesting. Tell me more."])
    session_id, client = await open_session(llm, use_llm)
    try:
        first = await synth_16k("So I developed a system with Django REST framework that had to handle "
                                "many different versions of a course, and then")
        second = await synth_16k("we had many bugs to fix.")
        third = await synth_16k("That's it.")
        await finish_greeting(client)
        await client.speak(first, realtime=False)  # speech_end → transcription of ~6 s starts
        await asyncio.sleep(0.4)  # the end-of-turn check is now waiting for that transcription...
        await client.speak(second, realtime=False)  # ...and gets cancelled by the new speech
        await asyncio.sleep(0.3)
        await client.speak(third, realtime=False)
        final = await client.until(is_type("transcript_final"), timeout=12)
        text = final["text"].lower()
        assert "django" in text and "bugs" in text and "that's it" in text
    finally:
        await client.ws.close()


async def test_ending_the_interview_mid_answer_keeps_the_answer(server, use_llm):
    llm = FakeLLM([GREETING])
    session_id, client = await open_session(llm, use_llm)
    try:
        await finish_greeting(client)
        await client.speak(await synth_16k("I worked on a billing system in Python."), realtime=False, end=False)
        await client.ws.send(json.dumps({"type": "end_session"}))
        await client.until(is_type("session_ended"), timeout=15)
    finally:
        await client.ws.close()
    turns = await get_turns(session_id)
    assert [t["role"] for t in turns] == ["interviewer", "candidate"]
    assert "billing" in turns[1]["full_text"].lower()
