"""initial schema

Revision ID: d59d72cb3f1f
Revises: 
Create Date: 2026-10-06 15:43:16.434254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd59d72cb3f1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accepted_variants',
    sa.Column('word', sa.Text(), nullable=True),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('accepted', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accepted_variants')),
    sa.UniqueConstraint('word', 'expected', 'accepted', name=op.f('uq_accepted_variants_word'), postgresql_nulls_not_distinct=True)
    )
    op.create_table('phoneme_calibration',
    sa.Column('phoneme', sa.Text(), nullable=False),
    sa.Column('accent', sa.Text(), server_default='en-us', nullable=False),
    sa.Column('native_mean', sa.Float(), nullable=False),
    sa.Column('native_std', sa.Float(), nullable=False),
    sa.Column('p05', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phoneme_calibration')),
    sa.UniqueConstraint('phoneme', 'accent', name=op.f('uq_phoneme_calibration_phoneme'))
    )
    op.create_table('tech_vocabulary',
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('phonemes', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('common_mistake_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tech_vocabulary')),
    sa.UniqueConstraint('term', name=op.f('uq_tech_vocabulary_term'))
    )
    op.create_table('users',
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('drill_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_error_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('ease', sa.Float(), server_default='2.5', nullable=False),
    sa.Column('interval_days', sa.Float(), server_default='0', nullable=False),
    sa.Column('repetitions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lapses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retired', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('pron_read', 'grammar_rewrite', 'tech_explain')", name=op.f('ck_drill_items_kind')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_drill_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drill_items'))
    )
    op.create_index(op.f('ix_drill_items_user_id'), 'drill_items', ['user_id'], unique=False)
    op.create_table('drill_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_drill_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drill_sessions'))
    )
    op.create_index(op.f('ix_drill_sessions_user_id'), 'drill_sessions', ['user_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_postings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_postings'))
    )
    op.create_index(op.f('ix_job_postings_user_id'), 'job_postings', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resumes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('user_phoneme_adjustments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phoneme', sa.Text(), nullable=False),
    sa.Column('word', sa.Text(), nullable=True),
    sa.Column('offset', sa.Float(), server_default='0', nullable=False),
    sa.Column('dismiss_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confirm_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_phoneme_adjustments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_phoneme_adjustments')),
    sa.UniqueConstraint('user_id', 'phoneme', 'word', name=op.f('uq_user_phoneme_adjustments_user_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_user_phoneme_adjustments_user_id'), 'user_phoneme_adjustments', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feedback_mode', sa.Text(), server_default='end', nullable=False),
    sa.Column('default_interviewer_style', sa.Text(), server_default='neutral', nullable=False),
    sa.Column('default_seniority', sa.Text(), server_default='senior', nullable=False),
    sa.Column('default_duration_min', sa.Integer(), server_default='30', nullable=False),
    sa.Column('turn_taking_mode', sa.Text(), server_default='auto', nullable=False),
    sa.Column('end_of_turn_silence_ms', sa.Integer(), server_default='1500', nullable=False),
    sa.Column('tts_voice', sa.Text(), server_default='af_heart', nullable=False),
    sa.Column('tts_speed', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('phoneme_threshold_k', sa.Float(), server_default='2.0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("default_interviewer_style IN ('friendly', 'neutral', 'tough')", name=op.f('ck_user_settings_default_interviewer_style')),
    sa.CheckConstraint("default_seniority IN ('mid', 'senior')", name=op.f('ck_user_settings_default_seniority')),
    sa.CheckConstraint("feedback_mode IN ('live', 'end', 'hybrid')", name=op.f('ck_user_settings_feedback_mode')),
    sa.CheckConstraint("turn_taking_mode IN ('auto', 'push_to_talk')", name=op.f('ck_user_settings_turn_taking_mode')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    op.create_table('drill_attempts',
    sa.Column('drill_session_id', sa.UUID(), nullable=False),
    sa.Column('drill_item_id', sa.UUID(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drill_item_id'], ['drill_items.id'], name=op.f('fk_drill_attempts_drill_item_id_drill_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drill_session_id'], ['drill_sessions.id'], name=op.f('fk_drill_attempts_drill_session_id_drill_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drill_attempts'))
    )
    op.create_index(op.f('ix_drill_attempts_drill_item_id'), 'drill_attempts', ['drill_item_id'], unique=False)
    op.create_index(op.f('ix_drill_attempts_drill_session_id'), 'drill_attempts', ['drill_session_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=True),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('seniority', sa.Text(), nullable=False),
    sa.Column('interviewer_style', sa.Text(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('feedback_mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("feedback_mode IN ('live', 'end', 'hybrid')", name=op.f('ck_interview_sessions_feedback_mode')),
    sa.CheckConstraint("interviewer_style IN ('friendly', 'neutral', 'tough')", name=op.f('ck_interview_sessions_interviewer_style')),
    sa.CheckConstraint("seniority IN ('mid', 'senior')", name=op.f('ck_interview_sessions_seniority')),
    sa.CheckConstraint("status IN ('active', 'completed', 'abandoned')", name=op.f('ck_interview_sessions_status')),
    sa.CheckConstraint("type IN ('system_design', 'technical', 'behavioral')", name=op.f('ck_interview_sessions_type')),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], name=op.f('fk_interview_sessions_job_posting_id_job_postings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_interview_sessions_resume_id_resumes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interview_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_sessions'))
    )
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('turns',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), server_default='', nullable=False),
    sa.Column('spoken_text', sa.Text(), server_default='', nullable=False),
    sa.Column('interrupted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('interrupted_at_char', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_ms', sa.Integer(), nullable=True),
    sa.Column('asr_words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_status', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("analysis_status IN ('pending', 'done', 'failed')", name=op.f('ck_turns_analysis_status')),
    sa.CheckConstraint("role IN ('interviewer', 'candidate')", name=op.f('ck_turns_role')),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_turns_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turns')),
    sa.UniqueConstraint('session_id', 'idx', name=op.f('uq_turns_session_id'))
    )
    op.create_index(op.f('ix_turns_session_id'), 'turns', ['session_id'], unique=False)
    op.create_table('audio_clips',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('source_turn_id', sa.UUID(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_turn_id'], ['turns.id'], name=op.f('fk_audio_clips_source_turn_id_turns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audio_clips_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_clips'))
    )
    op.create_index(op.f('ix_audio_clips_user_id'), 'audio_clips', ['user_id'], unique=False)
    op.create_table('errors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('drill_attempt_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), server_default='medium', nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('word', sa.Text(), nullable=True),
    sa.Column('expected_phonemes', sa.Text(), nullable=True),
    sa.Column('heard_phonemes', sa.Text(), nullable=True),
    sa.Column('phoneme_index', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('audio_clip_id', sa.UUID(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('pronunciation', 'grammar', 'technical', 'fluency', 'vocabulary')", name=op.f('ck_errors_kind')),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high')", name=op.f('ck_errors_severity')),
    sa.ForeignKeyConstraint(['audio_clip_id'], ['audio_clips.id'], name=op.f('fk_errors_audio_clip_id_audio_clips'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['drill_attempt_id'], ['drill_attempts.id'], name=op.f('fk_errors_drill_attempt_id_drill_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_errors_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], name=op.f('fk_errors_turn_id_turns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_errors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_errors'))
    )
    op.create_index(op.f('ix_errors_category'), 'errors', ['category'], unique=False)
    op.create_index(op.f('ix_errors_session_id'), 'errors', ['session_id'], unique=False)
    op.create_index(op.f('ix_errors_user_id'), 'errors', ['user_id'], unique=False)
    # FK cycle (errors -> drill_attempts -> drill_items -> errors): added after both tables exist
    op.create_foreign_key(op.f('fk_drill_items_source_error_id_errors'), 'drill_items', 'errors', ['source_error_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_drill_items_source_error_id_errors'), 'drill_items', type_='foreignkey')
    op.drop_index(op.f('ix_errors_user_id'), table_name='errors')
    op.drop_index(op.f('ix_errors_session_id'), table_name='errors')
    op.drop_index(op.f('ix_errors_category'), table_name='errors')
    op.drop_table('errors')
    op.drop_index(op.f('ix_audio_clips_user_id'), table_name='audio_clips')
    op.drop_table('audio_clips')
    op.drop_index(op.f('ix_turns_session_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_drill_attempts_drill_session_id'), table_name='drill_attempts')
    op.drop_index(op.f('ix_drill_attempts_drill_item_id'), table_name='drill_attempts')
    op.drop_table('drill_attempts')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_phoneme_adjustments_user_id'), table_name='user_phoneme_adjustments')
    op.drop_table('user_phoneme_adjustments')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_job_postings_user_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_drill_sessions_user_id'), table_name='drill_sessions')
    op.drop_table('drill_sessions')
    op.drop_index(op.f('ix_drill_items_user_id'), table_name='drill_items')
    op.drop_table('drill_items')
    op.drop_table('users')
    op.drop_table('tech_vocabulary')
    op.drop_table('phoneme_calibration')
    op.drop_table('accepted_variants')
    # ### end Alembic commands ###
