"""drill dedup and maturity

Revision ID: 62a37e06765c
Revises: d59d72cb3f1f
Create Date: 2026-10-06 17:16:40.211374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a37e06765c'
down_revision: Union[str, Sequence[str], None] = 'd59d72cb3f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drill_items', sa.Column('dedup_key', sa.Text(), nullable=False))
    op.add_column('drill_items', sa.Column('occurrences', sa.Integer(), server_default='1', nullable=False))
    op.add_column('drill_items', sa.Column('mature_streak', sa.Integer(), server_default='0', nullable=False))
    op.create_unique_constraint(op.f('uq_drill_items_user_id'), 'drill_items', ['user_id', 'dedup_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_drill_items_user_id'), 'drill_items', type_='unique')
    op.drop_column('drill_items', 'mature_streak')
    op.drop_column('drill_items', 'occurrences')
    op.drop_column('drill_items', 'dedup_key')
    # ### end Alembic commands ###
